version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: realtime_silakes
      MYSQL_USER: phoenix_user
      MYSQL_PASSWORD: password
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: always

volumes:
  mysql_data:
